robot_base_frame: $(arg frame)base_link

footprint:
  [[0.2755, -0.2585], [0.2755, 0.2585], [-0.2755, 0.2585], [-0.2755, -0.2585]]
robot_radius: 0.378

inscribed_radius: 0.378
circumscribed_radius: 0.378

inflation_radius: 0.5
cost_scaling_factor: 3.0

obstacle_range: 5.0
raytrace_range: 5.5

map_type: costmap
observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)front_laser,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
    obstacle_range: 2.5,
    raytrace_range: 3.0,
  }
