update_frequency: 5.0
publish_frequency: 5.0

obstacle_range: 5.0
raytrace_range: 5.5

transform_tolerance: 0.2

inflation_radius: 1.0
cost_scaling_factor: 5.0

map_type: costmap

semantic_layer:
    observation_sources: pedestrian pedestrian_moving pedestrian_type pedestrian_vel_x pedestrian_vel_y social_state

    pedestrian:
        topic: /crowdsim_agents/semantic/pedestrian

    pedestrian_moving:
        topic: /crowdsim_agents/semantic/pedestrian_moving

    pedestrian_type:
      topic: /crowdsim_agents/semantic/pedestrian_type

    pedestrian_vel_x:
      topic: /crowdsim_agents/semantic/pedestrian_vel_x
    
    pedestrian_vel_y:
      topic: /crowdsim_agents/semantic/pedestrian_vel_y

    social_state:
      topic: /crowdsim_agents/semantic/social_state