TebLocalPlannerROS:
  odom_topic: odom

  # Robot

  max_vel_x: 1.3
  max_vel_x_backwards: 0.2
  max_vel_y: 0.1
  max_vel_theta: 1.57
  min_vel_theta: -1.57
  acc_lim_x: 1.0
  acc_lim_theta: 20.0
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: polygon
    vertices: [[0.2755, -0.2585], [0.2755, 0.2585], [-0.2755, 0.2585], [-0.2755, -0.2585]]
  heading_scoring: true
