contestants:
  - name: teb-polite
    local_planner: teb
    inter_planner: polite

  - name: teb-aggressive
    local_planner: teb
    inter_planner: aggressive

  - name: rosnav-polite
    local_planner: rosnav
    inter_planner: polite

  - name: rosnav-aggressive
    local_planner: rosnav
    inter_planner: aggressive
    
  - name: cohan-polite
    local_planner: cohan
    inter_planner: polite

  - name: cohan-aggressive
    local_planner: cohan
    inter_planner: aggressive