controllers:
  - name: TrajectoryPlannerROS
    type: base_local_planner/TrajectoryPlannerROS

planners:
  - name: NavfnROS
    type: navfn/NavfnROS

controller_frequency: 5.0
controller_patience: 15.0
planner_frequency: 5.0
max_planning_retries: 5.0

TrajectoryPlannerROS:
  odom_topic: odom
  max_vel_x: $(arg speed)
   