TebLocalPlannerROS:
  # Trajectory

  dt_ref: 0.5
  max_vel_x: 0.8
  max_vel_x_backwards: 0.8
  max_vel_theta: 0.3
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.0
  footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
    type: point
    radius: 0.2 # for type "circular"
    line_start: [-0.3, 0.0] # for type "line"
    line_end: [0.3, 0.0] # for type "line"
    front_offset: 0.2 # for type "two_circles"
    front_radius: 0.2 # for type "two_circles"
    rear_offset: 0.2 # for type "two_circles"
    rear_radius: 0.2 # for type "two_circles"
    vertices: [[0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25,
        0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05]] # for type "polygon"

  # GoalTolerance

  min_obstacle_dist: 0.4
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  weight_obstacle: 50
  alternative_time_cost: false # not in use yet

  # Homotopy Class Planner

  simple_exploration: false
  obstacle_keypoint_offset: 0.1
