goal_reached:
  reward: 15

safe_distance:
  reward: -0.25

collision:
  reward: -15

approach_goal:
  pos_factor: 0.6
  neg_factor: 0.75
  _on_safe_dist_violation: true

reverse_drive:
  reward: -0.0002
  _on_safe_dist_violation: true

approach_globalplan:
  pos_factor: 0.1
  neg_factor: 0.15
  _on_safe_dist_violation: false

two_factor_velocity_difference:
  _on_safe_dist_violation: true

active_heading_direction:
  r_angle: 0.6
  iters: 40
  _on_safe_dist_violation: true

ped_type_collision:
  type: 1
  reward: -5

ped_type_safety_distance:
  type: 1
  reward: -0.1
  safety_distance: 1.25

ped_type_vel_constraint:
  type: 1
  penalty_factor: 0.05
  active_distance: 1.5