goal_reached:
  reward: 15

safe_distance:
  reward: -0.35

safe_distance_exp:
  reward: -0.15
  w_factor: 1.7
  punish_dist: 1.0

fixed_per_step:
  reward: -0.026

no_movement:
  reward: -0.027
  _on_safe_dist_violation: true

approach_goal:
  pos_factor: 0.1
  neg_factor: 0.5
  _on_safe_dist_violation: true

collision:
  reward: -14

# # Don't add if action range [0,1] or output points
# distance_travelled:
#   consumption_factor: 0.005
#   lin_vel_scalar: 1.0
#   ang_vel_scalar: 0.001
#   _on_safe_dist_violation: false

# reverse_drive:
#   reward: -0.08
#   _on_safe_dist_violation: true

# two_factor_velocity_difference:
#   alpha: 0.003
#   beta: 0.003
#   _on_safe_dist_violation: true

# approach_globalplan:
#   pos_factor: 0.1
#   neg_factor: 0.15
#   _on_safe_dist_violation: false

abrupt_velocity_change:
  vel_factors:
    "0": 0.15
    "1": 0.00
    "2": 0.08
  _on_safe_dist_violation: true

action_points_change:
  penalty_factor: 0.01

follow_tebplan:
  reward_factor: 0.0074
  is_integral_distance: false
  _on_safe_dist_violation: true