goal_reached:
  reward: 25

safe_distance:
  reward: -0.15

safe_distance_exp:
  reward: -0.25
  w_factor: 1.7
  punish_dist: 1.5

fixed_per_step:
  reward: -0.015

# # Don't add if action range [0,1] or output points
# no_movement:
#   reward: -0.015
#   _on_safe_dist_violation: true

approach_goal:
  pos_factor: 0.4
  neg_factor: 0.5
  _on_safe_dist_violation: true

collision:
  reward: -15

# # Don't add if action range [0,1] or output points
# distance_travelled:
#   consumption_factor: 0.005
#   lin_vel_scalar: 1.0
#   ang_vel_scalar: 0.001
#   _on_safe_dist_violation: false

# # not used in globalplan_collector_unit.py
# approach_globalplan:
#   pos_factor: 0.3
#   neg_factor: 0.5
#   _on_safe_dist_violation: false
# follow_globalplan:
#   min_dist_to_path: 0.5
#   reward_factor: 0.1
#   _on_safe_dist_violation: false

# reverse_drive:
#   reward: -0.03
#   _on_safe_dist_violation: true

# # Request modify if action range [0,1] or output points
# abrupt_velocity_change:
#   vel_factors:
#     "0": 0.1
#     "1": 0.00
#     "2": 0.03
#   _on_safe_dist_violation: true

# # Request modify if action range [0,1] or output points
# root_velocity_difference:
#   k: -0.01
#   _on_safe_dist_violation: true

# two_factor_velocity_difference:
#   alpha: 0.003
#   beta: 0.003
#   _on_safe_dist_violation: true

# abrupt_velocity_change:
#   vel_factors:
#     "0": 0.35
#     "1": 0.07
#     "2": 0.15
#   _on_safe_dist_violation: true