robot_base_frame: $(arg frame)base_footprint
# # burger\originBot
# robot_radius: 0.113

# inscribed_radius: 0.113
# circumscribed_radius: 0.113

# turtlebot2
robot_radius: 0.177

inscribed_radius: 0.177
circumscribed_radius: 0.177

observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)base_scan,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }

