TebLocalPlannerROS:
  odom_topic: odom

  # Trajectory

  # 轨迹优化过程中考虑的最大样本数。增加样本数可以提高轨迹的质量，但会增加计算量。
  max_samples: 200
  # 是否允许轨迹从后退运动开始。
  allow_init_with_backwards_motion: false
  # 全局路径中两个连续路径点之间的最大距离，超过该距离路径规划器将自动插入新的路径点。设置为负值禁用此功能。
  global_plan_viapoint_sep: -1
  # 从全局路径中剪除已经通过的路径部分的距离阈值。这有助于保持轨迹的更新与机器人的实际位置同步。
  global_plan_prune_distance: 1
  # 是否使用精确的圆弧长度进行计算。开启这个选项可以提高路径的准确性，但可能会增加计算成本。
  exact_arc_length: false
  # 是否发布路径规划过程的反馈信息。这对于调试和监控路径规划过程可能很有用。
  publish_feedback: false

  # Robot

  # 机器人在x轴方向的最大速度。
  max_vel_x: 0.8
  # 机器人向后的最大速度。对于不支持后退的机器人，此值应为0。
  max_vel_x_backwards: 0.0
  # 对于非全向机器人，此值应为0。
  max_vel_y: 0.0
  # 机器人的最大旋转速度。
  max_vel_theta: 2.23
  acc_lim_x: 3.0
  acc_lim_theta: 3.0
  # 机器人的最小转弯半径。对于差动驱动机器人，此值通常为0，意味着机器人可以原地旋转。
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: circle
    radius: 0.2  # 机器人的半径，单位为米

  # GoalTolerance

